#!/bin/bash
/c/Users/SARAH/bin:/mingw32/bin:/usr/local/bin:/usr/bin:/bin:/mingw32/bin:/usr/bin:/c/Users/SARAH/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files/GitHub CLI:/cmd:/c/HashiCorp/Vagrant/bin:/c/Users/SARAH/AppData/Local/Microsoft/WindowsApps:/c/Users/SARAH/AppData/Local/Programs/Microsoft VS Code/bin:/usr/bin/vendor_perl:/usr/bin/core_perl
:/action
